feat add async fn for transports
decentraland/js-sdk-toolchain pull request #348
Opened 2022-12-02 18:18 UTC by gonpombo8

2022-12-05 23:26 UTC, menduz approved these changes
Amazing job. Only left one comment 🚀

2022-12-05 23:26 UTC, menduz commented on packages/@dcl/ecs/src/systems/crdt/index.ts
> +    }
What is the rationale behind this if? It seems like the addTransport should not care about anything related to the type of the transport. i.e. we sould be able to add 15 ws transports if desired

2022-12-06 01:32 UTC, menduz requested changes
This impl is not working as intended. Will push tests soon to another PR

2022-12-08 19:35 UTC, gonpombo8 commented
Closed via https://github.com/decentraland/js-sdk-toolchain/pull/352

2022-12-08 19:35 UTC, closed without merging