Add files-watcher for 'start' command
decentraland/js-sdk-toolchain pull request #398
Opened 2023-01-31 17:13 UTC by nicoecheza

2023-02-07 15:46 UTC, menduz requested changes

2023-02-07 15:46 UTC, menduz commented on packages/@dcl/sdk/cli/commands/preview/wire.ts
> +  previewComponents: PreviewComponents,
```suggestion
  components: CliComponents,
  dir: string,
```

Please unify components into CliComponents, delete PreviewComponents

2023-02-07 15:49 UTC, nicoecheza commented on packages/@dcl/sdk/cli/commands/preview/wire.ts
> +        if (await shouldUpdateScene(components, dir, file)) {
we are only watching files inside the `bin` directory :D

2023-02-07 16:46 UTC, nicoecheza commented on packages/@dcl/sdk/cli/commands/preview/wire.ts
> +        if (await shouldUpdateScene(components, dir, file)) {
fixed 👌

2023-02-07 17:00 UTC, menduz approved these changes

2023-02-08 13:31 UTC, nicoecheza commented on packages/@dcl/sdk/cli/commands/preview/wire.ts
> +  }
this condition is useless if you have a proper `.dclignore`, but leaving it there won't harm anyone for now. We should add those extensions + node_modules + some-other-stuff to the defaults to make sure we don't add watchers for unnecessary files. 

Issue for this created [here](https://github.com/decentraland/sdk/issues/599)

2023-02-08 13:31 UTC, merged