feat: Add Metrics Limits overlay
decentraland/js-sdk-toolchain pull request #890
Opened 2024-02-06 20:06 UTC by cyaiox

This PR adds the scene limits metrics.

![image](https://github.com/decentraland/js-sdk-toolchain/assets/3170051/6f3dd659-6ca7-40aa-bc41-5d490848f026)

https://docs.decentraland.org/creator/development-guide/sdk7/scene-limitations/#scene-limitation-rules

2024-02-06 20:28 UTC, nearnshaw commented
@cyaiox  amazing how fast you got this working ❤️ 

I'm testing in the link to inspector from this PR

it seems that when I change the parcel layout in the component of the Scene entity, this UI doesn't react. It always says 2x2 Land, with limits of a 2x2, even if I add or remove parcels from the list.

Another thing I'm noticing is that you reach the max textures very fast. Most of the items in the asset packs reuse 3 or 4 common textures. But even if I duplicate a same item many times, each copy adds to the number of textures. I should really only count unique textures, repeated textures should only be counted once

2024-02-07 11:57 UTC, cazala commented on packages/@dcl/inspector/src/components/Renderer/Metrics/Metrics.tsx
> +            {scene.layout.base.x}x{scene.layout.base.y} LAND
the "COLSxROWS" layout only makes sense for the builder, but for scenes with irregular shapes it does not work. For example you could have a scene with the shape of an "S" and that is not translatable to a COLSxROWS format.

Also `layout.base` is not being used correctly in this context. The base is the corner of the scene where to originate the x,y,z coordinate system, but is not the number of columns or rows neither.

Also for Worlds the LAND part is not relevant.

So I would say we simply remove the COLSxROWS label from the UI.

2024-02-07 20:16 UTC, cazala requested changes
I see the metrics do refresh when i add new entities (ie drag n drop or duplicate) but it does not when i delete an entity.

2024-02-07 21:06 UTC, cazala approved these changes

2024-02-07 21:08 UTC, merged